/**
 * Browser-side Supabase client (astroli-web).
 *
 * Uses @supabase/ssr's createBrowserClient so the auth session is stored in
 * cookies, not localStorage. This keeps it in sync with the middleware and
 * server-side clients, which both read the same cookie-backed session.
 *
 * Call getBrowserClient().auth.getSession() anywhere on the client to read
 * the current user's session metadata (student_id, teacher_id, role) without
 * a network round-trip (Supabase serves from its in-memory cache).
 *
 * Server-side admin client lives in lib/supabase-server.ts.
 * Import it from there in API routes — NEVER import that file here, because
 * this file is included in the browser bundle.
 *
 * Required env vars (.env.local):
 *   NEXT_PUBLIC_SUPABASE_URL       — Supabase → Settings → API
 *   NEXT_PUBLIC_SUPABASE_ANON_KEY  — Supabase → Settings → API
 */

import { createBrowserClient as createSSRBrowserClient } from '@supabase/ssr';

// Database type — generated by `npx supabase gen types typescript` once schema exists.
export type Database = any;

type BrowserClient = ReturnType<typeof createSSRBrowserClient<Database>>;
let _browserClient: BrowserClient | null = null;

/**
 * SSR-aware singleton browser client. Always use this instead of creating a
 * new client — multiple instances cause duplicate Realtime subscriptions.
 */
export function getBrowserClient(): BrowserClient {
  if (typeof window === 'undefined') {
    throw new Error('getBrowserClient() must only be called in the browser.');
  }
  if (!_browserClient) {
    _browserClient = createSSRBrowserClient<Database>(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    );
  }
  return _browserClient;
}
