import { createClient } from '@supabase/supabase-js';

// ---------------------------------------------------------------------------
// Supabase client setup for astroli-web
//
// TWO clients, two different access levels:
//
//  supabaseAdmin  — server-side only (API routes). Uses the service role key
//                   which bypasses Row Level Security. This is equivalent to
//                   being a DB superuser. Never expose this key to the browser.
//
//  supabaseBrowser — browser-side (React hooks, Realtime subscriptions).
//                   Uses the public anon key which respects RLS policies.
//                   Safe to embed in client bundles.
//
// Required env vars (add to .env.local):
//   NEXT_PUBLIC_SUPABASE_URL        — from Supabase → Settings → API
//   NEXT_PUBLIC_SUPABASE_ANON_KEY   — from Supabase → Settings → API
//   SUPABASE_SERVICE_ROLE_KEY       — from Supabase → Settings → API (secret)
// ---------------------------------------------------------------------------

// Database type — generated by `npx supabase gen types typescript` once schema exists.
// Replace `Database` with the generated type for full type safety on all queries.
// Until then, 'any' is used as a placeholder; queries still work, just un-typed.
export type Database = any;

// supabaseAdmin lives in lib/supabase-server.ts (server-only).
// Import it from there in API routes — never import it here, because this file
// is also imported by client-side hooks and browser bundles.

/** Browser client for Realtime and read-only queries from React components. */
export function createBrowserClient() {
  return createClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  );
}

// Singleton browser client — reuse the same instance across all hooks.
let _browserClient: ReturnType<typeof createBrowserClient> | null = null;

export function getBrowserClient() {
  if (typeof window === 'undefined') {
    throw new Error('getBrowserClient() must only be called in the browser.');
  }
  if (!_browserClient) {
    _browserClient = createBrowserClient();
  }
  return _browserClient;
}

