-- Migration: master_message_sequence
-- Transcript order must be exact. created_at alone is not enough: messages
-- written in one statement share a timestamp, and a uuid tiebreaker orders them
-- randomly — which showed up as a dive transcript reading out of order.
-- A serial column makes insertion order the source of truth.

ALTER TABLE master_dive_messages
  ADD COLUMN IF NOT EXISTS seq bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS master_dive_messages_session_seq_idx
  ON master_dive_messages (session_id, seq);
